# Change these first
owner: V12NSXA # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: NoChay-Website
    url: https://nochay.com
  - name: KVM-1
    url: http://157.90.184.234
  - name: KVM-2
    url: http://87.118.126.170

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nochay.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/mast
  name: NoChay-Status
  introTitle: "Aktuller System-Status:"
  navbar:
    - title: NoChay
      href: https://nochay.com
    - title: NoChay-Discord
      href: https://discord.gg/FzSdZESR2U

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Edit
